-- Generated by Mocodo 4.2.12

CREATE TABLE AYANT_DROIT (
  matricule       VARCHAR(42) NOT NULL,
  nom_ayant_droit VARCHAR(42) NOT NULL,
  lien            VARCHAR(42),
  PRIMARY KEY (matricule, nom_ayant_droit),
  FOREIGN KEY (matricule) REFERENCES EMPLOYE (matricule)
);

CREATE TABLE COMPOSER (
  ref_piece_composee   VARCHAR(42) NOT NULL,
  ref_piece_composante VARCHAR(42) NOT NULL,
  quantite             VARCHAR(42),
  PRIMARY KEY (ref_piece_composee, ref_piece_composante),
  FOREIGN KEY (ref_piece_composee) REFERENCES PIECE (ref_piece),
  FOREIGN KEY (ref_piece_composante) REFERENCES PIECE (ref_piece)
);

CREATE TABLE DEPARTEMENT (
  num_departement VARCHAR(42) NOT NULL,
  nom_departement VARCHAR(42),
  PRIMARY KEY (num_departement)
);

CREATE TABLE EMPLOYE (
  matricule       VARCHAR(42) NOT NULL,
  nom_employe     VARCHAR(42),
  num_departement VARCHAR(42) NOT NULL,
  PRIMARY KEY (matricule),
  FOREIGN KEY (num_departement) REFERENCES DEPARTEMENT (num_departement)
);

CREATE TABLE FOURNIR (
  num_projet  VARCHAR(42) NOT NULL,
  ref_piece   VARCHAR(42) NOT NULL,
  num_societe VARCHAR(42) NOT NULL,
  qte_fournie VARCHAR(42),
  PRIMARY KEY (num_projet, ref_piece, num_societe),
  FOREIGN KEY (num_projet) REFERENCES PROJET (num_projet),
  FOREIGN KEY (ref_piece) REFERENCES PIECE (ref_piece),
  FOREIGN KEY (num_societe) REFERENCES SOCIETE (num_societe)
);

CREATE TABLE PIECE (
  ref_piece     VARCHAR(42) NOT NULL,
  libelle_piece VARCHAR(42),
  PRIMARY KEY (ref_piece)
);

CREATE TABLE PROJET (
  num_projet            VARCHAR(42) NOT NULL,
  nom_projet            VARCHAR(42),
  matricule_responsable VARCHAR(42) NULL,
  PRIMARY KEY (num_projet),
  FOREIGN KEY (matricule_responsable) REFERENCES EMPLOYE (matricule)
);

CREATE TABLE REQUERIR (
  num_projet  VARCHAR(42) NOT NULL,
  ref_piece   VARCHAR(42) NOT NULL,
  qte_requise VARCHAR(42),
  PRIMARY KEY (num_projet, ref_piece),
  FOREIGN KEY (num_projet) REFERENCES PROJET (num_projet),
  FOREIGN KEY (ref_piece) REFERENCES PIECE (ref_piece)
);

CREATE TABLE SOCIETE (
  num_societe      VARCHAR(42) NOT NULL,
  raison_sociale   VARCHAR(42),
  num_societe_mere VARCHAR(42) NULL,
  PRIMARY KEY (num_societe),
  FOREIGN KEY (num_societe_mere) REFERENCES SOCIETE (num_societe)
);

CREATE TABLE TRAVAILLER (
  matricule  VARCHAR(42) NOT NULL,
  num_projet VARCHAR(42) NOT NULL,
  PRIMARY KEY (matricule, num_projet),
  FOREIGN KEY (matricule) REFERENCES EMPLOYE (matricule),
  FOREIGN KEY (num_projet) REFERENCES PROJET (num_projet)
);

INSERT INTO TRAVAILLER VALUES
  ('test1', 'test2'),
  ('test1.1', 'test2.2');

SELECT * FROM TRAVAILLER